name: Car booking validation
run-name: ${{ github.actor }} is running e2e test
on: [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        working-directory: task2/
        run: chmod +x ./gradlew && ./gradlew assemble

      - name: test
        working-directory: task2/
        run: export BROWSER=firefox && ./gradlew test

      - name: check-if-file-is-generated
        working-directory: task2/
        run: cat src/test/kotlin/*.txt
