name: Car booking validation
run-name: ${{ github.actor }} is running e2e test
on: [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: cd task2/ && ls -la && chmod +x ./gradlew

      - name: build
        run: cd task2/ && ./gradlew assemble

      - name: test
        run: cd task2/ && ./gradlew test