name: Car booking validation
run-name: ${{ github.actor }} is running e2e test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew assemble

  test:
    runs-on: java-19
    steps:
      - run: ./gradlew test
